In [13]:
from source_functions import *
from estimate_BLP import *

# Part 2.2: Demand-side estimation, 100 markets

## Load data and set function arguments

In [15]:
df_3p, alphas_3p = load_mat_data('Simulation Data/100markets3products.mat', 3, 100)
df_5p, alphas_5p = load_mat_data('Simulation Data/100markets5products.mat', 5, 100)

sigma_alpha_init = 1.0 #initial guess
df = df_3p #data
alphas = alphas_3p #random coefficients on prices
mode = "demand_side" #demand-side moments only

In [ ]:
out_demandside = estimate_BLP(df, alphas, sigma_alpha_init, mode, verbose_print = 3, scale_delta_guess = 5)

#============================================================================#
#== Solving the MPEC optimization routine
#============================================================================#
| niter |f evals|CG iter|  obj func   |tr radius |   opt    |  c viol  | penalty  |CG stop|
|-------|-------|-------|-------------|----------|----------|----------|----------|-------|
|   1   |   1   |   0   | +7.0000e+00 | 1.00e+00 | 1.04e-04 | 1.00e+00 | 1.00e+00 |   0   |
|   2   |   2   |   1   | +3.6812e+00 | 5.60e+00 | 9.14e-05 | 7.25e-01 | 1.00e+00 |   1   |
|   3   |   3   |   2   | +1.8076e-02 | 3.14e+01 | 2.87e-05 | 4.12e-01 | 1.70e+02 |   1   |
|   4   |   4   |   3   | +1.1035e+00 | 1.76e+02 | 3.00e-03 | 8.38e-02 | 2.90e+03 |   1   |
|   5   |   5   |   4   | +1.0374e+00 | 1.76e+02 | 3.84e-03 | 2.20e-02 | 2.90e+03 |   1   |
|   6   |   6   |   5   | +8.2412e-01 | 1.76e+02 | 3.54e-03 | 6.52e-03 | 2.90e+03 |   1   |
|   7   |   7   |   6   | +6.5876e-01 | 1.76e+02 | 3.18e-03 | 1.

In [52]:
out_demandside['beta_hat']

array([[4.92818632],
       [0.95515674],
       [1.02872379]])

In [54]:
out_demandside['alpha_hat']

0.9675675769687724

In [21]:
out_demandside['sigma_alpha_hat']

0.988803761232181

# Part 2.2g: Demand-side instruments, 10 markets
Load the data and set function arguments:

In [4]:
df_3p10m, alphas_3p10m = load_mat_data('Simulation Data/10markets3products.mat', 3, 10)

#### Function arguments
mode = "demand_side" #demand-side moments only

In [1]:
out_demandside_10m=estimate_BLP(df_3p10m, alphas_3p10m, sigma_alpha_init, mode, verbose_print = 3, scale_delta_guess = 1, max_iter=10000)

In [8]:
out_demandside_10m['beta_hat']

array([[2.61933023],
       [0.42100499],
       [1.36710302]])

In [9]:
out_demandside_10m['alpha_hat']

0.6553970510094898

In [10]:
out_demandside_10m['sigma_alpha_hat']

0.5041133184257544

In [11]:
out_demandside_10m['se']

array([0.06732948, 2.49792306, 1.0830104 , 0.46744008, 0.93377222])

In [13]:
out_demandside_10m['delta_hat']

array([[ 1.86533923],
       [-2.12141033],
       [ 4.05913902],
       [ 6.95258272],
       [ 3.69674902],
       [ 6.6412869 ],
       [-3.99973352],
       [ 1.38139637],
       [ 2.1689793 ],
       [ 1.38473689],
       [-0.13766322],
       [-2.41411314],
       [ 1.91022051],
       [ 2.57301979],
       [-0.26126805],
       [ 0.94162019],
       [ 1.47393124],
       [ 3.66253282],
       [ 1.34997316],
       [ 2.40093755],
       [ 1.92687823],
       [ 3.59306967],
       [-2.16580292],
       [ 3.04896491],
       [ 2.60760996],
       [-3.09186598],
       [ 0.6924699 ],
       [ 3.08296056],
       [ 1.78019891],
       [-2.24204089]])

# Part 2.3: Using price as a moment. 

Estimate $\theta$ assming incorrectly that $E[\xi|p]=0$ within each market. 

Load the data and set function arguments:

In [2]:
out_demandside_pmoment = estimate_BLP(df, alphas, 0.8, "p_exercise", verbose_print = 3, scale_delta_guess = 3, max_iter=10000)

In [20]:
out_demandside_pmoment['beta_hat']

array([[5.23096072],
       [1.01114156],
       [1.08674171]])

In [21]:
out_demandside_pmoment['alpha_hat']

0.8914277431679762

In [22]:
out_demandside_pmoment['sigma_alpha_hat']

1.1507497157653737

# Part 3.1: Using the cost shifter as a moment

Estimate assuming  $E[\xi|X, w^\text{cost}]=0$. 

Load the data and set function arguments:

In [165]:
#out_demandside_wcost = estimate_BLP(df, alphas, sigma_alpha_init, "supply_W", verbose_print=3)

# Joint estimation

In [17]:
out = estimate_BLP(df, alphas, sigma_alpha_init, "supply_joint", verbose_print=3)

#============================================================================#
#== Solving the MPEC optimization routine
#============================================================================#


ValueError: Non-hashable static arguments are not supported. An error occurred while trying to hash an object of type <class 'numpy.ndarray'>, [[0.4591674  4.88418038 0.97169801 ... 0.82530039 3.26780763 1.79057662]
 [0.16433075 2.47256783 1.23110119 ... 1.58345129 2.97901192 2.38555584]
 [1.17755    2.15053704 0.72417763 ... 5.03107334 1.29392047 1.74659196]
 ...
 [2.91021758 1.17936163 1.15869411 ... 6.00564717 1.98396329 0.80617328]
 [3.94929048 0.75798081 2.55450762 ... 3.47182545 0.88511087 2.33866059]
 [0.37894156 1.08619779 0.43807837 ... 2.81537652 1.28581925 0.9528541 ]]. The error was:
TypeError: unhashable type: 'numpy.ndarray'
